# Generated by Django 2.1 on 2018-08-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField(blank=True, db_column='Book', null=True)),
                ('chapter', models.IntegerField(blank=True, db_column='Chapter', null=True)),
                ('versecount', models.IntegerField(blank=True, db_column='Versecount', null=True)),
                ('verse', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'Bible',
                'managed': False,
            },
        ),
    ]
